spring:
  datasource:
    url: 
    port: 3306
    username: 
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jta:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8088
